config: !!python/object:ts3l.utils.switchtab_utils.switchtab_config.SwitchTabConfig
  alpha: 1.0
  category_dims: []
  corruption_rate: 0.3
  dropout_rate: 0.3
  encoder_depth: 4
  ffn_factor: 2.0
  hidden_dim: 200
  initialization: kaiming_uniform
  input_dim: 108
  loss_fn: MSELoss
  loss_hparams: {}
  metric: mean_absolute_percentage_error
  metric_hparams: {}
  n_head: 2
  optim: AdamW
  optim_hparams:
    lr: 0.0001
    weight_decay: 5.0e-05
  output_dim: 1
  random_seed: 42
  scheduler: null
  scheduler_hparams: null
  task: regression
  u_label: -1
